### ISSUE TITLE
Snippets are now one line

### ISSUE THREAD

**Issue by jrock2004** [josemarluedke/ember-vim-snippets#5]
Not sure what happen but now when I load a snippet its all one line

```
snippet model "Route: model(...) { ... }"
model(params = {}) {,	return this.store.query('${1}', params);,},
endsnippet
```

This is what gets loaded when I do `model <tab>`

```
model(params = {}) {,	return this.store.query(' ', params);,},
```

I think the snippet now needs to be

```
snippet model "Route: model(...) { ... }"
model(params = {}) {
    return this.store.query('${1}', params);
},
endsnippet
```

**Comment by josemarluedke** [comment]
Fixed with #6. Thanks for reporting this.

**Comment by jrock2004** [comment]
I just got back to updating this and I still having some issue

```
model(params = {}) {,	return this.store.query('', params);,},
```
